name: shooter
description: A simple dart game
version: 0.0.1
homepage: https://github.com/GOGO98901/dart-shooter
environment:
  sdk: '>=1.0.0'

dependencies:
  json_object: ^1.0.19
  dart_to_js_script_rewriter: "^1.0.1"
  browser: any

transformers:
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
